Fix #814
supabase-community/supabase-py pull request #846
Opened 2024-07-03 19:07 UTC by juancarlospaco

## What kind of change does this PR introduce?

- Fix #814

2024-07-04 19:21 UTC, mansueli approved these changes

2024-07-08 13:37 UTC, silentworks requested changes
This should follow how we are setting `postgrest_client_timeout` in other libraries. It should be passed through the constructor and not be added via a method through a private variable.

2024-07-17 12:26 UTC, J0 approved these changes

2024-07-24 13:58 UTC, silentworks approved these changes

2024-07-24 13:58 UTC, merged